export const SHOP = '/'
export const ITEM_PAGE = '/item'
export const BASKET = '/basket'
export const AUTH = '/auth'
export const ELECTRONICS = '/electronics'
export const JEWERELY = '/jewerely'
export const MENCLOTHING = '/menclothing'
export const WOMENCLOTHING = '/womenclothing'
